### ISSUE TITLE
Category Colors

### ISSUE THREAD

**Issue by robmyers** [creativecommons/list#243] opened 2015-04-08 00:47 UTC
Android 5.1 Nexus 6
03_30_15 version.

On the "Pick Categories" screen, the "People" category is presented as white text on a lime green background. This isn't very contrasty and so is less legible than the other categories (squint and look at it to blur your eyes and get a feel for the relative contrast).

The red and green square next to each other on the "Pick Categories" screen will not be as clear to someone with red/green color blindness.

The colors on the "Pick Categories" screen don't seem to relate semantically to the categories on the other screens. This prevents those users who can scan for different categories of requests by background colour from doing so, which may be a good or bad thing depending on  how we wish to work with users' attention.

**Comment by mattl** [comment] 2015-04-08 01:53
We have a ticket open to update them.

**Comment by mattl** [comment] 2015-04-08 14:53
Duplicate of #192

**Closed by mattl** 2015-04-08 14:53 UTC
Labels: android app
