### ISSUE TITLE
Cannot tell if image has been successfully taken and uploaded on app

### ISSUE THREAD

**Issue by mindspillage** [creativecommons/list#112] opened 2015-01-07 20:45 UTC
I can't tell whether an upload has been successful or not--after I take a picture from my list there's no indication whatsoever that anything happened.

**Comment by mattl** [comment] 2015-01-07 20:53
What phone and version of Android do you have?

**Comment by mindspillage** [comment] 2015-01-07 21:00
Galaxy Nexus, Android 4.3.

**Comment by mattl** [comment] 2015-01-07 21:58
Duplicate of #100

**Closed by mattl** 2015-01-07 21:58 UTC
