### ISSUE TITLE
Turning phone sideways sometimes changes list item

### ISSUE THREAD

**Issue by elliotharmon** [creativecommons/list#111] opened 2015-01-07 20:43 UTC
When browsing through list items, I tilt my phone between landscape and portrait. Sometimes, the app switches to a different list item.

Droid Mini, Android 4.4

**Comment by mattl** [comment] 2015-01-07 21:56
Duplicate of #105 -- orientation is messy.

**Closed by mattl** 2015-01-07 21:56 UTC
